# -*- coding: utf-8 -*-
"""class_pythonteacher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbDIwqmnwM_yQGCVv5BqJzZfVGe6uXQy
"""

class PythonTeacher:
    def __init__(
        self,
        name: str,
        experience_years: int,
        courses: list = None,
    ):
        """
        Создание объекта "Учитель по Python".

        :param name: Имя учителя.
        :param experience_years: Опыт преподавания (в годах).
        :param courses: Список преподаваемых курсов (по умолчанию базовый курс).
        """
        if not isinstance(name, str):
          raise TypeError("Имя должно быть записано строкой")
        self.name = name
        if not isinstance(experience_years, (int, float)):
          raise TypeError("Опыт работы должен быть записан цифрами")
        if experience_years < 0:
          raise ValueError("Опыт работы должен быть больше или равен 0!")
        self.experience_years = experience_years
        if not isinstance(name, str):
          raise TypeError("Курс должен быть записано строкой")
        self.courses = courses if courses else ["Основы Python"]
        self.students = []  # Список студентов

    def __str__(self) -> str:
        """Строковое представление учителя."""
        return (
            f"Учитель Python: {self.name}\n"
            f"Опыт: {self.experience_years} лет\n"
            f"Курсы: {', '.join(self.courses)}"
        )

    def teach(self, topic: str) -> str:
        """
        Провести урок по заданной теме.

        :param topic: Тема урока.
        :return: Строка с процессом преподавания.
        """
        return f"{self.name} преподает тему: '{topic}'. 🎓"

    def add_student(self, student_name: str) -> None:
        """
        Добавить студента в список.

        :param student_name: Имя студента.
        """
        self.students.append(student_name)
        print(f"Студент {student_name} добавлен в группу!")

    def __len__(self) -> int:
        """Количество студентов у учителя."""
        return len(self.students)